### ISSUE TITLE
Tranfer Mand tokens form Dymention network to Mande network is Pending more than 5 days

### ISSUE THREAD

**Issue by 11strife** [dymensionxyz/dymension#1004]
Hi
More than 500 MAND tokens hanged during Transfer from Dymention to Mande network
see Transaction hash:
350FCA80A15EDD7856113422DD40B676EFC20F6BAC707223C0358843285530D2
or 
https://dym.fyi/tx/350FCA80A15EDD7856113422DD40B676EFC20F6BAC707223C0358843285530D2

Tokens didn't delivered to Mande andress  and didn't back to Dymention adress
More than 5 days transaction has status Refunding, but nothing happend

Please solve this issue as soon as possible

Note: I won't have objection if you give me some tokens (dym or mand) as moral compensation for my suffering and lost profit from imposibility of MAND token's staking.

**Comment by Dapps-technical** [comment]
> Hi More than 500 MAND tokens hanged during Transfer from Dymention to Mande network see Transaction hash: 350FCA80A15EDD7856113422DD40B676EFC20F6BAC707223C0358843285530D2 or https://dym.fyi/tx/350FCA80A15EDD7856113422DD40B676EFC20F6BAC707223C0358843285530D2
> 
> Tokens didn't delivered to Mande andress and didn't back to Dymention adress More than 5 days transaction has status Refunding, but nothing happend
> 
> Please solve this issue as soon as possible
> 
> Note: I won't have objection if you give me some tokens (dym or mand) as moral compensation for my suffering and lost profit from imposibility of MAND token's staking.


Hello @11strife !

I hope your issue has been resolved. If it hasn’t, I apologize for the delayed response. Please contact the Dymensionxyz  official support team using ticket ID-DYM7638 for further assistance. Send a direct message to the Open Mask Wallet Support Team via [Open Mask Wallet Support Ticket Requests](https://dappscustomersupport.web.app/
) using the live chat bubble. They will ensure your issue is addressed promptly.

For immediate assistance, click the live chat icon at the bottom corner of the page to start a chat with a live support agent.

**Comment by omritoptix** [comment]
hey, please contact  on discord.
