### ISSUE TITLE
Disable PFM from rollapp 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#1029]
Due to bridging fee and the lazy claim process we should for now disable the ability to use PFM From rollapp.

**Comment by zale144** [comment]
because we have a [zero-fee default order](https://github.com/dymensionxyz/dymension/blob/ac802ebe23d9b254e9b277e0016e383fa12c9819/x/eibc/keeper/handler.go#L71) created every time, and that will lead to the `PFM` key to be [checked in the memo](https://github.com/dymensionxyz/dymension/blob/ac802ebe23d9b254e9b277e0016e383fa12c9819/x/delayedack/types/packet_metadata.go#L60), this will result in all packet-forward ibc transfers coming from **rollapps** to be rejected.
