### ISSUE TITLE
hard fork: refactor `revision` and `revision_start_height` to array 

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension#1450]
as discussed should be a list of numbers and start heights.

_Originally posted by @omritoptix in https://github.com/dymensionxyz/dymension/pull/1354#discussion_r1835328138_

**Comment by keruch** [comment]
Basically, today after a hard fork, we bump the rollapp revision and set the `revision_start_height`. For example, if at height 100 we had a hard fork and the previous revision was 1, then now on the rollapp object we have `revision=2` and `revision_start_height=101`. The revision is necessary for the hard fork to function and for syncing.

The problem is that currently, the revision number and start height are singular fields. However, because a rollapp can be forked multiple times, we need to turn these fields into a list to keep the history of all revision bumps and their start heights.

Current rollapp revision field: https://github.com/dymensionxyz/dymension/blob/5deae8512b53e41b64c0cba1209151802ada06d9/proto/dymensionxyz/dymension/rollapp/rollapp.proto#L79
