### ISSUE TITLE
Rollapp query list commands improvement suggestions

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#247]
1. I believe all rollapp list commands should be forced to have a rollapp-id otherwise it floods with data which I don't see the usecase for. i.e don't see why would I want to get all info on all rollapps in one query assuming I can get it by rollapp id. 

2. Per command

- `list-rollapp-state-info`- Dont think this is necessary as I believe detailed state info should be provided given a specific state index and not as a list of state info.
- `list-block-height-to-finalization-queue`  list all block_height_to_finalization_queue - not clear what this command is doing 
- `list-state-index`  - I believe this is redundant as if forcing to provide `rollapp-id` as suggested before it's the same as `show-latest-state-index`

**Comment by ItzhakBokris** [comment]
**First, we need to pay attention to the differences between latest-state and latest-finalized-state. Latest-state refers to the most recently updated state of a specific rollapp, whereas latest-finalized-state represents the most recent state that has been successfully finalized for a given rollapp.**

Rollapp Module Commands

- `list-rollapp` - Returns a list of all the registered rollapps in the hub. Without the pagination parameter, it returns the first 100 rollapps.
- `show-rollapp [rollapp-id]` - Returns an info object of the specified rollapp.
- `list-block-height-to-finalization-queue` - Returns, for each finalization height, a list of states waiting to be finalized when the hub's block height reaches that finalization height. Without the pagination parameter, it returns the first 100 finalization heights.
- `show-block-height-to-finalization-queue [finalized-height]` - Returns, for the specified finalization height, a list of states waiting to be finalized when the hub's block height reaches that finalization height.
- `list-rollapp-state-info` - Returns all the state-info of all the rollapps, ordered by the hub's block creation height. Without the pagination parameter, it returns the first 100 states.
- `show-rollapp-state-info --rollapp-id=[rollapp-id] --rollapp-height=[rollapp-height]` - Shows the state-info of the specified rollapp and rollapp-height.
- `show-rollapp-state-info --rollapp-id=[rollapp-id] --index=[state-index]` - Shows the state-info of the specified rollapp and state-index.
- `list-state-index` - Returns, for each rollapp, the current (latest) index of the last updated state.
- `show-latest-state-index [rollapp-id]` - Shows the current (latest) index of the last updated state for the specified rollapp.
- `show-latest-finalized-state-info [rollapp-id]` - Shows latest state that was finalized for the specified rollapp.


Suggested Changes

- The `list-rollapp` command should return lighter and more usable objects, including the following fields: rollapp-id, latest-state-index (and possibly latest-finalized-state-index), which are more relevant for the command's use cases.
- The response of the `show-rollapp` command should include the latest-state-index (and maybe latest-finalized-state-index) in addition to other information.
- The results of the `list-block-height-to-finalization-queue` and `show-block-height-to-finalization-queue` commands should be returned in reverse order (by default), as the latest states are more relevant. However, the specific use cases for these commands are not clear.
- The `list-rollapp-state-info` command should require a rollapp-id as an argument, as fetching all states of all rollapps is not a practical use case. Additionally, the unnecessary block-description list, which can be obtained through the `show-rollapp-state-info` command, should be removed to avoid excessive response size. Furthermore, the results should be returned in reverse order (by default), prioritizing the latest states.
- The `show-rollapp-state-info` commands should accept a rollapp-id as an argument instead of a flag. By default, it should return the latest state-info unless rollapp-height or index flags are specified. Optionally, a hub-height flag can also be considered.
- The `list-state-index` command is redundant since the latest-state-index for each rollapp can already be obtained through the `list-rollapp` command.
- The `show-latest-state-index` command is unnecessary since its purpose was primarily to fetch the correct rollapp-state-info from the `show-rollapp-state-info` command but we will modified it to return the latest state-info by default so we don't need the `show-latest-state-index` anymore. Users still interested in the index can utilize the `show-rollapp` command.
- The `show-latest-finalized-state-info` command can be removed if the `show-rollapp-state-info` command is enhanced with an additional "finalized" flag to retrieve the desired information.
