### ISSUE TITLE
hub not producing snapshots

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#285]
Seems like the hub, as being ran by silknodes, doesn't produce snapshots and hence there is no ability for a state sync.

**Comment by mtsitrin** [comment]
should cover the following issue as well:

`I looked at the state sync just now and noticed Dymension reports that you need 436 (!!) snapshot chunks in order to state sync. That's the most I've seen on any Comsos chain by far. Is there are reason for this? Is this something the team should look at? A chain like 35-C should have a lot less, closer to 15-30 chunks. <@945304344402735175>`

**Comment by mtsitrin** [comment]
reference
https://medium.com/tendermint/tendermint-core-state-sync-for-developers-70a96ba3ee35
